# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='date time')),
                ('totH', models.FloatField(verbose_name='day tot hour presence')),
                ('offH', models.FloatField(verbose_name='day tot hour off')),
                ('travel', models.CharField(max_length=50)),
                ('travel_cost', models.IntegerField(verbose_name='business travel cost')),
                ('overnigth_cost', models.IntegerField(verbose_name='business travel overnigth cost')),
                ('inM', models.TimeField(verbose_name='morning entry time')),
                ('outM', models.TimeField(verbose_name='morning exit time')),
                ('inA', models.TimeField(verbose_name='afternoon entry time')),
                ('outA', models.TimeField(verbose_name='afternoon exit time')),
            ],
        ),
    ]
