# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytime',
            name='travel_cost',
            field=models.IntegerField(default=0, verbose_name='business travel cost'),
        ),
    ]
