# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180625_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytime',
            name='id',
        ),
        migrations.AlterField(
            model_name='daytime',
            name='day',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False, verbose_name='date time'),
        ),
    ]
